apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service_doc
  annotations:
    backstage.io/techdocs-ref: value
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
